In [1]:
import os
from ase import Atoms
from ase.calculators.dftb import Dftb
from ase.io import write, read
from ase.build import molecule
from ase.optimize import LBFGS
from ase.optimize.sciopt import SciPyFminBFGS
import numpy as np
import shutil

print(shutil.which("dftb+"))
os.environ["DFTB_PREFIX"] = "/home/cschmidt/dftb_par/3ob-3-1/"

directory_path = '/data/cschmidt/heidelberg_HOMO_LUMO_anya'
geom_opt_name = 'geom_opt.xyz'

#atoms = molecule('H2O')
atoms = Atoms('CH4', positions=[[0, 0, 0], [0.8, 1.5, -0.4], [-0.1, 0, -0.514], [-0.1, 1.0, -1.514], [-0.1, 2.0, -1.514]])
print(atoms.positions)
# Define parameters for DFTB calculation
calculator = Dftb(atoms=atoms,
            label='dftb',
            Driver_='ConjugateGradient',
            Driver_MaxForceComponent=1e-4,
            Driver_MaxSteps=1000,
            Hamiltonian_SCC='Yes',
            Hamiltonian_SCCTolerance=1e-10,
            Hamiltonian_MaxSCCIterations=250,
            Hamiltonian_MaxAngularMomentum_='',
            Hamiltonian_MaxAngularMomentum_O='p',
            Hamiltonian_MaxAngularMomentum_H='s',
            Hamiltonian_MaxAngularMomentum_C='p',
            Options_WriteBandOut='Yes',
            Hamiltonian_ThirdOrderFull = 'Yes',
            Hamiltonian_HubbardDerivs_ = '',
            Hamiltonian_HubbardDerivs_O = -0.1575,
            Hamiltonian_HubbardDerivs_H = -0.1857,
            Hamiltonian_HubbardDerivs_C = -0.14,
            # Hamiltonian_Filling = 'Fermi {}',
            directory=".")

atoms.set_calculator = calculator

# Run the optimization
calculator.calculate(atoms)

# The 'geo_end.gen' file written by the ASE calculator
# (containing the initial geometry), has been overwritten
# by DFTB+ and now contains the final, optimized geometry.
opt_file_name = 'geo_end.gen'
opt_file_path = os.path.join(os.getcwd(), opt_file_name)
final = read(opt_file_path)
geom_opt_path = os.path.join(os.getcwd(), geom_opt_name)
write(geom_opt_path, final)

/usr/local/bin/dftb+
[[ 0.     0.     0.   ]
 [ 0.8    1.5   -0.4  ]
 [-0.1    0.    -0.514]
 [-0.1    1.    -1.514]
 [-0.1    2.    -1.514]]


In [33]:
# Perform the geometry optimization
optimizer = LBFGS(atoms, trajectory='H2O.traj', use_line_search=False, damping=0.1)
optimizer.run(fmax = 0.0001)
# Access the optimized geometry
optimized_positions = atoms.positions
print(optimized_positions)

       Step     Time          Energy         fmax
LBFGS:    0 16:54:43     -110.541149        0.0017
LBFGS:    1 16:54:48     -110.541149        0.0017
LBFGS:    2 16:54:53     -110.541149        0.0016
LBFGS:    3 16:54:54     -110.541149        0.0014
LBFGS:    4 16:54:57     -110.541149        0.0013
LBFGS:    5 16:55:00     -110.541149        0.0012
LBFGS:    6 16:55:03     -110.541149        0.0011
LBFGS:    7 16:55:06     -110.541149        0.0010
LBFGS:    8 16:55:07     -110.541149        0.0009
LBFGS:    9 16:55:11     -110.541149        0.0008
LBFGS:   10 16:55:15     -110.541149        0.0051
LBFGS:   11 16:55:17     -110.541149        0.0009


KeyboardInterrupt: 