In [1]:
import numpy as np
import os

In [2]:
TARGET_DIR = "/lustre/work/ws/ws1/ka_he8978-dipeptide/training/10_amp_qmmm/B2-PLYP_def2-QZVPP_D3BJ/04_sereina_support/lukas-scripted-models/numpy-regenerate/dalanine"

In [3]:
os.chdir(TARGET_DIR) # Change to the target directory

# Load data from .npy files
orca_coordinates = np.load('orca_coordinates.npy')  # shape (N_atoms, 3)
orca_species = np.load('orca_species.npy')          # shape (N_atoms,)
orca_pc_charges = np.load('orca_pc_charges.npy')    # shape (N_pc,)
orca_pc_coordinates = np.load('orca_pc_coordinates.npy')  # shape (N_pc, 3)

print("Loaded data shapes:")
print(f"orca_coordinates: {orca_coordinates.shape}")
print(f"orca_species: {orca_species.shape}")
print(f"orca_pc_charges: {orca_pc_charges.shape}")
print(f"orca_pc_coordinates: {orca_pc_coordinates.shape}")


Loaded data shapes:
orca_coordinates: (100000, 22, 3)
orca_species: (100000, 22)
orca_pc_charges: (100000, 1986)
orca_pc_coordinates: (100000, 1986, 3)


In [6]:
target_index = 0

target_coordinates = orca_coordinates[target_index]
target_species = orca_species[target_index]
target_pc_charges = orca_pc_charges[target_index]
target_pc_coordinates = orca_pc_coordinates[target_index]

In [6]:
# Prepare ORCA input file content
orca_input_lines = []
orca_input_lines.append('! B3LYP def2-SVP TightSCF')  # Example header, adjust as needed
orca_input_lines.append('%pointcharges "charges.pc"')
orca_input_lines.append('* xyz 0 1')

# Add atoms
for atom, coord in zip(target_species, target_coordinates):
    orca_input_lines.append(f"{atom} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}")

orca_input_lines.append('*')

# Write ORCA input file
with open('orca_input.inp', 'w') as f:
    for line in orca_input_lines:
        f.write(line + '\n')

# Prepare point charges file
with open('charges.pc', 'w') as f:
    for charge, coord in zip(target_pc_charges, target_pc_coordinates):
        f.write(f"{charge:.6f} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}\n")

In [4]:
orca_energies = np.load('orca_energies.npy')  # shape (N_atoms, N_atoms)
orca_engrad = np.load('orca_engrad.npy')  # shape (N_atoms, N_atoms, 3)
orca_dipole = np.load('orca_dipoles.npy')  # shape (N_atoms, 3)
orca_quadrupole = np.load('orca_quadrupoles.npy')  # shape (N_atoms, 3, 3)

In [7]:
target_energy = orca_energies[target_index]
target_engrad = orca_engrad[target_index]
target_dipole = orca_dipole[target_index]
target_quadrupole = orca_quadrupole[target_index]

print("Target energy:", target_energy)
print("Target engrad:")
print(target_engrad)
print("Target dipole:")
print(target_dipole)
print("Target quadrupole:")
print(target_quadrupole)

Target energy: -495.735874339068
Target engrad:
[[-6.26129534e-03  2.68436776e-03 -9.96102243e-03]
 [-8.88797531e-03 -5.28345791e-03 -1.20265856e-02]
 [ 1.27047009e-02 -4.97541737e-03  1.04472092e-02]
 [ 3.43561836e-03  8.91311027e-04  1.80701122e-02]
 [ 2.12357842e-02 -1.60525541e-03 -3.64224412e-02]
 [-2.40450723e-02  9.00927340e-05  4.52611070e-03]
 [-2.18013412e-02  3.47017113e-02  3.39537224e-02]
 [ 2.32630451e-02 -1.09474909e-02 -1.30482781e-02]
 [ 5.42397198e-03  1.02659331e-02 -8.45929528e-03]
 [-2.03306297e-03 -2.96070017e-02  2.21755713e-02]
 [-8.98779463e-03  1.72371758e-02 -7.98331913e-03]
 [ 1.07375532e-02 -9.13586757e-04  2.01299308e-03]
 [-2.70452167e-03 -5.36621429e-03 -5.59290800e-05]
 [-4.03536938e-03 -1.10699929e-02 -5.83130816e-03]
 [-7.01620103e-03 -1.67042712e-03  1.08245487e-02]
 [ 2.57293679e-02  1.52486148e-02  1.05618445e-03]
 [-4.66585338e-02 -1.84266889e-02 -9.22273273e-02]
 [ 5.92480739e-02  1.39434784e-02  6.15267423e-02]
 [-1.41815849e-02 -3.25812651e-02 

In [14]:
H2ev = 27.2114  # Hartree to eV conversion factor
B2A = 0.529177  # Bohr to Angstrom conversion factor
H_B2eV_A = H2ev / B2A  # Hartree per Bohr to eV per Angstrom conversion factor
eB2eA = B2A # Dipole conversion factor, e*Bohr to e*Angstrom
eB2Debye = 1/0.3934393 # Conversion factor from e*Bohr to Debye

In [ ]:
# Benzene values
energy = 232.203897370932*H2ev
print("Energy:")
print(energy)
grads = np.array([[-0.003767745,  0.005739884,   -0.000340584],
[ 0.012802701, -0.002196129,   -0.009005250],
[ 0.003366848,  0.011597964,    0.012479080],
[-0.004796674, -0.011363084,   -0.003556601],
[-0.005451275,  0.009036961,    0.006476033],
[ 0.007552621,  0.000930378,   -0.011542708],
[-0.012232895,  0.000471327,    0.016000127],
[ 0.009087252, -0.001081523,   -0.006960005],
[-0.019489322, -0.022108267,    0.006199577],
[-0.001613787,  0.009420481,    0.006379653],
[ 0.015934452,  0.003654104,   -0.012356001],
[-0.000438949, -0.003223007,   -0.003642466],])*H_B2eV_A
print("Grads:")
print(grads)

dipole = np.array([-0.16674, -0.08729, -0.41694])*eB2Debye
print("Dipole:")
print(dipole)

Energy:
6318.593132919379
Grads:
[[-0.19374541  0.29515697 -0.01751355]
 [ 0.65834195 -0.1129296  -0.46306899]
 [ 0.17313044  0.59639183  0.64170067]
 [-0.24665512 -0.5843138  -0.18288794]
 [-0.28031608  0.46469964  0.33301131]
 [ 0.38837174  0.047842   -0.59355045]
 [-0.62904132  0.02423663  0.82276035]
 [ 0.46728571 -0.0556142  -0.35789817]
 [-1.00218214 -1.13685383  0.31879536]
 [-0.08298434  0.48442105  0.32805524]
 [ 0.81938321  0.18790175 -0.63537169]
 [-0.02257169 -0.16573383 -0.1873033 ]]
Dipole:
[-0.42380108 -0.22186396 -1.05973145]


In [ ]:
energy = 